language: node_js
node_js:
- 10

branches:
  only:
  - gh-pages

install:
- npm install

before_script:
- sleep 300

script:
- npm run test-firefox-prod && npm run test-chrome-prod

cache:
  npm: true
  directories:
  - ~/.cache

env:
  global:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable