language: node_js
node_js:
- 10

services:
- docker

sudo: required

branches:
  only:
  - master
  - gh-pages

before_script:
- ./scripts/docker_install_run.sh
- npm install
- sleep 20
- docker ps -a

script:
- npm run test

cache:
  npm: true
  directories:
  - ~/.cache

env:
  global:
  - MOZ_HEADLESS=1
addons:
  firefox: latest